name: parry.rs CI build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yarn install
        run: corepack enable && yarn
      - run: ./generate_user_guides.sh
      - run: yarn build
